service: nh-bookmark
frameworkVersion: "4"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
  httpApi:
    cors: true
  environment:
    DB_ACCESS_KEY_ID: ${env:DB_ACCESS_KEY_ID}
    DB_SECRET_ACCESS_KEY: ${env:DB_SECRET_ACCESS_KEY}

functions:
  api:
    handler: main.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ["aws-sdk"]
    target: "node20"
    define: { "require.resolve": undefined }
    platform: "node"
    concurrency: 10
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
