service: nh-bookmark
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
  httpApi:
    cors: true
  environment:
    DB_ACCESS_KEY_ID: ${env:DB_ACCESS_KEY_ID}
    DB_SECRET_ACCESS_KEY: ${env:DB_SECRET_ACCESS_KEY}

functions:
  api:
    handler: main.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: webpack.config.ts
